#!/usr/bin/env python3

import smbus
import time
import subprocess

I2C_ADDR = 0x27
I2C_BUS = 1

class LCD:
    def __init__(self):
        self.bus = smbus.SMBus(I2C_BUS)
        self.backlight = 0x08

    def write(self, data):
        self.bus.write_byte(I2C_ADDR, data | self.backlight)

    def pulse(self, data):
        self.write(data | 0x04)
        time.sleep(0.0005)
        self.write(data & ~0x04)
        time.sleep(0.0001)

    def send(self, data, mode):
        high = mode | (data & 0xF0)
        low = mode | ((data << 4) & 0xF0)

        self.pulse(high)
        self.pulse(low)

    def init(self):
        time.sleep(0.05)

        self.pulse(0x30)
        time.sleep(0.005)

        self.pulse(0x30)
        time.sleep(0.005)

        self.pulse(0x30)
        time.sleep(0.005)

        self.pulse(0x20)

        self.send(0x28, 0)
        self.send(0x0C, 0)
        self.send(0x06, 0)
        self.send(0x01, 0)

        time.sleep(0.005)

    def clear(self):
        self.send(0x01, 0)
        time.sleep(0.005)

    def display(self, text, line):

        addresses = {
            1: 0x80,
            2: 0xC0,
            3: 0x94,
            4: 0xD4
        }

        self.send(addresses[line], 0)

        text = text.ljust(20)

        for char in text[:20]:
            self.send(ord(char), 1)

def get_ip():
    try:
        return subprocess.check_output(
            ['hostname', '-I']
        ).decode().split()[0]
    except:
        return "No IP"

lcd = LCD()
lcd.init()

while True:

    config = {}

    with open("config.txt") as f:
        for line in f:
            key, value = line.strip().split("=")
            config[key] = value

    lcd.clear()

    lcd.display(config["line1"], 1)
    lcd.display("IP Address:", 2)
    lcd.display(get_ip(), 3)

    time.sleep(5)
